INSERT INTO sics_database.courses (course_name) VALUES ('Biochemical Techniques');
INSERT INTO sics_database.courses (course_name) VALUES ('Biochemistry');
INSERT INTO sics_database.courses (course_name) VALUES ('Biomaterials');
INSERT INTO sics_database.courses (course_name) VALUES ('Biomechanics');
INSERT INTO sics_database.courses (course_name) VALUES ('Biomedical Instrumentation');
INSERT INTO sics_database.courses (course_name) VALUES ('Branding and Identity Design');
INSERT INTO sics_database.courses (course_name) VALUES ('Cell Biology');
INSERT INTO sics_database.courses (course_name) VALUES ('Climate Change and Sustainability');
INSERT INTO sics_database.courses (course_name) VALUES ('Comparative Politics');
INSERT INTO sics_database.courses (course_name) VALUES ('Content Marketing Strategies');
INSERT INTO sics_database.courses (course_name) VALUES ('Cybersecurity Risk Management');
INSERT INTO sics_database.courses (course_name) VALUES ('Data Analytics for Marketing');
INSERT INTO sics_database.courses (course_name) VALUES ('Data Structures and Algorithms');
INSERT INTO sics_database.courses (course_name) VALUES ('Database Management Systems');
INSERT INTO sics_database.courses (course_name) VALUES ('Digital Media Design');
INSERT INTO sics_database.courses (course_name) VALUES ('Ecology and Ecosystems');
INSERT INTO sics_database.courses (course_name) VALUES ('Environmental Chemistry');
INSERT INTO sics_database.courses (course_name) VALUES ('Environmental Policy and Management');
INSERT INTO sics_database.courses (course_name) VALUES ('Enzymology');
INSERT INTO sics_database.courses (course_name) VALUES ('Ethical Hacking');
INSERT INTO sics_database.courses (course_name) VALUES ('Foreign Policy Analysis');
INSERT INTO sics_database.courses (course_name) VALUES ('General Biochemistry');
INSERT INTO sics_database.courses (course_name) VALUES ('Genetics');
INSERT INTO sics_database.courses (course_name) VALUES ('Global Security Studies');
INSERT INTO sics_database.courses (course_name) VALUES ('Human Rights in International Relations');
INSERT INTO sics_database.courses (course_name) VALUES ('Information Security Policy');
INSERT INTO sics_database.courses (course_name) VALUES ('International Organizations');
INSERT INTO sics_database.courses (course_name) VALUES ('International Relations');
INSERT INTO sics_database.courses (course_name) VALUES ('International Relations Theory');
INSERT INTO sics_database.courses (course_name) VALUES ('Introduction to Biomedical Engineering');
INSERT INTO sics_database.courses (course_name) VALUES ('Introduction to Cybersecurity');
INSERT INTO sics_database.courses (course_name) VALUES ('Introduction to Digital Marketing');
INSERT INTO sics_database.courses (course_name) VALUES ('Introduction to Environmental Science');
INSERT INTO sics_database.courses (course_name) VALUES ('Introduction to Graphic Design');
INSERT INTO sics_database.courses (course_name) VALUES ('Introduction to Molecular Biology');
INSERT INTO sics_database.courses (course_name) VALUES ('Introduction to Political Science');
INSERT INTO sics_database.courses (course_name) VALUES ('Introduction to Programming');
INSERT INTO sics_database.courses (course_name) VALUES ('Medical Imaging');
INSERT INTO sics_database.courses (course_name) VALUES ('Metabolism');
INSERT INTO sics_database.courses (course_name) VALUES ('Molecular Genetics');
INSERT INTO sics_database.courses (course_name) VALUES ('Network Security');
INSERT INTO sics_database.courses (course_name) VALUES ('Political Theory');
INSERT INTO sics_database.courses (course_name) VALUES ('Public Policy Analysis');
INSERT INTO sics_database.courses (course_name) VALUES ('Search Engine Optimization (SEO)');
INSERT INTO sics_database.courses (course_name) VALUES ('Social Media Marketing');
INSERT INTO sics_database.courses (course_name) VALUES ('Software Engineering Principles');
INSERT INTO sics_database.courses (course_name) VALUES ('Structural Biochemistry');
INSERT INTO sics_database.courses (course_name) VALUES ('Typography and Layout');
INSERT INTO sics_database.courses (course_name) VALUES ('User Experience Design');
INSERT INTO sics_database.courses (course_name) VALUES ('Web Development');
