INSERT INTO sics_database.interests (interest_name) VALUES ('Brand Identity');
INSERT INTO sics_database.interests (interest_name) VALUES ('Conservation Efforts');
INSERT INTO sics_database.interests (interest_name) VALUES ('Consumer Behavior');
INSERT INTO sics_database.interests (interest_name) VALUES ('Cooking');
INSERT INTO sics_database.interests (interest_name) VALUES ('Cross-Cultural Communication');
INSERT INTO sics_database.interests (interest_name) VALUES ('Data Analysis');
INSERT INTO sics_database.interests (interest_name) VALUES ('Environmental Policy');
INSERT INTO sics_database.interests (interest_name) VALUES ('Ethical Hacking');
INSERT INTO sics_database.interests (interest_name) VALUES ('Gaming');
INSERT INTO sics_database.interests (interest_name) VALUES ('Genetic Research');
INSERT INTO sics_database.interests (interest_name) VALUES ('Global Affairs');
INSERT INTO sics_database.interests (interest_name) VALUES ('Health Technology');
INSERT INTO sics_database.interests (interest_name) VALUES ('Hiking');
INSERT INTO sics_database.interests (interest_name) VALUES ('International Diplomacy');
INSERT INTO sics_database.interests (interest_name) VALUES ('Laboratory Techniques');
INSERT INTO sics_database.interests (interest_name) VALUES ('Medical Device Innovation');
INSERT INTO sics_database.interests (interest_name) VALUES ('Metabolic Pathways');
INSERT INTO sics_database.interests (interest_name) VALUES ('Music');
INSERT INTO sics_database.interests (interest_name) VALUES ('Network Security');
INSERT INTO sics_database.interests (interest_name) VALUES ('Photography');
INSERT INTO sics_database.interests (interest_name) VALUES ('Political Campaigning');
INSERT INTO sics_database.interests (interest_name) VALUES ('Protein Analysis');
INSERT INTO sics_database.interests (interest_name) VALUES ('Reading');
INSERT INTO sics_database.interests (interest_name) VALUES ('Social Media Trends');
INSERT INTO sics_database.interests (interest_name) VALUES ('Software Development');
INSERT INTO sics_database.interests (interest_name) VALUES ('Sports');
INSERT INTO sics_database.interests (interest_name) VALUES ('Traveling');
INSERT INTO sics_database.interests (interest_name) VALUES ('Visual Storytelling');
