UPDATE sics_database.interests SET interest_name = 'Brand Identity' WHERE id = 14;
UPDATE sics_database.interests SET interest_name = 'Conservation Efforts' WHERE id = 7;
UPDATE sics_database.interests SET interest_name = 'Consumer Behavior' WHERE id = 16;
UPDATE sics_database.interests SET interest_name = 'Cooking' WHERE id = 22;
UPDATE sics_database.interests SET interest_name = 'Cross-Cultural Communication' WHERE id = 12;
UPDATE sics_database.interests SET interest_name = 'Data Analysis' WHERE id = 18;
UPDATE sics_database.interests SET interest_name = 'Environmental Policy' WHERE id = 8;
UPDATE sics_database.interests SET interest_name = 'Ethical Hacking' WHERE id = 19;
UPDATE sics_database.interests SET interest_name = 'Gaming' WHERE id = 28;
UPDATE sics_database.interests SET interest_name = 'Genetic Research' WHERE id = 1;
UPDATE sics_database.interests SET interest_name = 'Global Affairs' WHERE id = 11;
UPDATE sics_database.interests SET interest_name = 'Health Technology' WHERE id = 4;
UPDATE sics_database.interests SET interest_name = 'Hiking' WHERE id = 23;
UPDATE sics_database.interests SET interest_name = 'International Diplomacy' WHERE id = 10;
UPDATE sics_database.interests SET interest_name = 'Laboratory Techniques' WHERE id = 2;
UPDATE sics_database.interests SET interest_name = 'Medical Device Innovation' WHERE id = 3;
UPDATE sics_database.interests SET interest_name = 'Metabolic Pathways' WHERE id = 6;
UPDATE sics_database.interests SET interest_name = 'Music' WHERE id = 25;
UPDATE sics_database.interests SET interest_name = 'Network Security' WHERE id = 20;
UPDATE sics_database.interests SET interest_name = 'Photography' WHERE id = 24;
UPDATE sics_database.interests SET interest_name = 'Political Campaigning' WHERE id = 9;
UPDATE sics_database.interests SET interest_name = 'Protein Analysis' WHERE id = 5;
UPDATE sics_database.interests SET interest_name = 'Reading' WHERE id = 27;
UPDATE sics_database.interests SET interest_name = 'Social Media Trends' WHERE id = 15;
UPDATE sics_database.interests SET interest_name = 'Software Development' WHERE id = 17;
UPDATE sics_database.interests SET interest_name = 'Sports' WHERE id = 26;
UPDATE sics_database.interests SET interest_name = 'Traveling' WHERE id = 21;
UPDATE sics_database.interests SET interest_name = 'Visual Storytelling' WHERE id = 13;
