INSERT INTO sics_database.students (name, major, email, year) VALUES ('Liam O\'Connor', 'Biochemistry', 'liam.oconnor@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Sofia Garcia', 'Computer Science', 'sofia.garcia@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Mohammed Al-Rashid', 'Biomedical Engineering', 'mohammed.rashid@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Yuki Tanaka', 'Molecular Biology', 'yuki.tanaka@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Aisha Ahmed', 'Environmental Science', 'aisha.ahmed@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('John Smith', 'Political Science', 'john.smith@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Maria Gonzalez', 'International Relations', 'maria.gonzalez@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Chen Wei', 'Graphic Design', 'chen.wei@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Priya Patel', 'Digital Marketing', 'priya.patel@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Carlos Mendez', 'Computer Science', 'carlos.mendez@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Fatima Hassan', 'Environmental Science', 'fatima.hassan@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Daniel Kim', 'Cybersecurity', 'daniel.kim@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Katarina Petrova', 'Biochemistry', 'katarina.petrova@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Amir Abdullah', 'Molecular Biology', 'amir.abdullah@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Alex Wong', 'Biomedical Engineering', 'alex.wong@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Ravi Desai', 'Environmental Science', 'ravi.desai@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Sophia Martinez', 'Political Science', 'sophia.martinez@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Nathan Brown', 'International Relations', 'nathan.brown@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Leila Zafar', 'Graphic Design', 'leila.zafar@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Andre Souza', 'Digital Marketing', 'andre.souza@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Ella Johansson', 'Computer Science', 'ella.johansson@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Arjun Singh', 'Cybersecurity', 'arjun.singh@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Mei Ling', 'Biochemistry', 'mei.ling@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Emmanuel Okoro', 'Molecular Biology', 'emmanuel.okoro@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Giulia Rossi', 'Biomedical Engineering', 'giulia.rossi@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Helena Nunes', 'Environmental Science', 'helena.nunes@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Michael O’Leary', 'Political Science', 'michael.oleary@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Kaito Nakamura', 'International Relations', 'kaito.nakamura@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Pavel Ivanov', 'Graphic Design', 'pavel.ivanov@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Isabella Santos', 'Digital Marketing', 'isabella.santos@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Maya Lee', 'Computer Science', 'maya.lee@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Nina Korhonen', 'Cybersecurity', 'nina.korhonen@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Derek McKenzie', 'Biochemistry', 'derek.mckenzie@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Serena Chang', 'Molecular Biology', 'serena.chang@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Omar Nasser', 'Biomedical Engineering', 'omar.nasser@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Lucas Johnson', 'Environmental Science', 'lucas.johnson@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Tara Sharma', 'Political Science', 'tara.sharma@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Hana Abdi', 'International Relations', 'hana.abdi@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Boris Zubov', 'Graphic Design', 'boris.zubov@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Kelsey Davis', 'Digital Marketing', 'kelsey.davis@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Selina Meyer', 'Computer Science', 'selina.meyer@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Julian Torres', 'Cybersecurity', 'julian.torres@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Eva Novak', 'Biochemistry', 'eva.novak@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Noah Baker', 'Molecular Biology', 'noah.baker@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Mohammed Qasim', 'Biomedical Engineering', 'mohammed.qasim@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Sophia Jones', 'Environmental Science', 'sophia.jones@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Lina Wu', 'Political Science', 'lina.wu@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Olu Jacobs', 'International Relations', 'olu.jacobs@example.com', '2027');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Fatimah Jamal', 'Graphic Design', 'fatimah.jamal@example.com', '2025');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Jorge Diaz', 'Digital Marketing', 'jorge.diaz@example.com', '2026');
INSERT INTO sics_database.students (name, major, email, year) VALUES ('Tatiana Kuznetsov', 'Computer Science', 'tatiana.kuznetsov@example.com', '2027');
