UPDATE sics_database.courses SET course_name = 'Biochemical Techniques' WHERE id = 15;
UPDATE sics_database.courses SET course_name = 'Biochemistry' WHERE id = 4;
UPDATE sics_database.courses SET course_name = 'Biomaterials' WHERE id = 9;
UPDATE sics_database.courses SET course_name = 'Biomechanics' WHERE id = 7;
UPDATE sics_database.courses SET course_name = 'Biomedical Instrumentation' WHERE id = 10;
UPDATE sics_database.courses SET course_name = 'Branding and Identity Design' WHERE id = 34;
UPDATE sics_database.courses SET course_name = 'Cell Biology' WHERE id = 2;
UPDATE sics_database.courses SET course_name = 'Climate Change and Sustainability' WHERE id = 19;
UPDATE sics_database.courses SET course_name = 'Comparative Politics' WHERE id = 22;
UPDATE sics_database.courses SET course_name = 'Content Marketing Strategies' WHERE id = 39;
UPDATE sics_database.courses SET course_name = 'Cybersecurity Risk Management' WHERE id = 49;
UPDATE sics_database.courses SET course_name = 'Data Analytics for Marketing' WHERE id = 40;
UPDATE sics_database.courses SET course_name = 'Data Structures and Algorithms' WHERE id = 42;
UPDATE sics_database.courses SET course_name = 'Database Management Systems' WHERE id = 44;
UPDATE sics_database.courses SET course_name = 'Digital Media Design' WHERE id = 33;
UPDATE sics_database.courses SET course_name = 'Ecology and Ecosystems' WHERE id = 17;
UPDATE sics_database.courses SET course_name = 'Environmental Chemistry' WHERE id = 20;
UPDATE sics_database.courses SET course_name = 'Environmental Policy and Management' WHERE id = 18;
UPDATE sics_database.courses SET course_name = 'Enzymology' WHERE id = 12;
UPDATE sics_database.courses SET course_name = 'Ethical Hacking' WHERE id = 48;
UPDATE sics_database.courses SET course_name = 'Foreign Policy Analysis' WHERE id = 28;
UPDATE sics_database.courses SET course_name = 'General Biochemistry' WHERE id = 11;
UPDATE sics_database.courses SET course_name = 'Genetics' WHERE id = 3;
UPDATE sics_database.courses SET course_name = 'Global Security Studies' WHERE id = 27;
UPDATE sics_database.courses SET course_name = 'Human Rights in International Relations' WHERE id = 30;
UPDATE sics_database.courses SET course_name = 'Information Security Policy' WHERE id = 50;
UPDATE sics_database.courses SET course_name = 'International Organizations' WHERE id = 29;
UPDATE sics_database.courses SET course_name = 'International Relations' WHERE id = 23;
UPDATE sics_database.courses SET course_name = 'International Relations Theory' WHERE id = 26;
UPDATE sics_database.courses SET course_name = 'Introduction to Biomedical Engineering' WHERE id = 6;
UPDATE sics_database.courses SET course_name = 'Introduction to Cybersecurity' WHERE id = 46;
UPDATE sics_database.courses SET course_name = 'Introduction to Digital Marketing' WHERE id = 36;
UPDATE sics_database.courses SET course_name = 'Introduction to Environmental Science' WHERE id = 16;
UPDATE sics_database.courses SET course_name = 'Introduction to Graphic Design' WHERE id = 31;
UPDATE sics_database.courses SET course_name = 'Introduction to Molecular Biology' WHERE id = 1;
UPDATE sics_database.courses SET course_name = 'Introduction to Political Science' WHERE id = 21;
UPDATE sics_database.courses SET course_name = 'Introduction to Programming' WHERE id = 41;
UPDATE sics_database.courses SET course_name = 'Medical Imaging' WHERE id = 8;
UPDATE sics_database.courses SET course_name = 'Metabolism' WHERE id = 13;
UPDATE sics_database.courses SET course_name = 'Molecular Genetics' WHERE id = 5;
UPDATE sics_database.courses SET course_name = 'Network Security' WHERE id = 47;
UPDATE sics_database.courses SET course_name = 'Political Theory' WHERE id = 24;
UPDATE sics_database.courses SET course_name = 'Public Policy Analysis' WHERE id = 25;
UPDATE sics_database.courses SET course_name = 'Search Engine Optimization (SEO)' WHERE id = 38;
UPDATE sics_database.courses SET course_name = 'Social Media Marketing' WHERE id = 37;
UPDATE sics_database.courses SET course_name = 'Software Engineering Principles' WHERE id = 43;
UPDATE sics_database.courses SET course_name = 'Structural Biochemistry' WHERE id = 14;
UPDATE sics_database.courses SET course_name = 'Typography and Layout' WHERE id = 32;
UPDATE sics_database.courses SET course_name = 'User Experience Design' WHERE id = 35;
UPDATE sics_database.courses SET course_name = 'Web Development' WHERE id = 45;
