UPDATE sics_database.students SET name = 'Liam O\'Connor', major = 'Biochemistry', email = 'liam.oconnor@example.com', year = '2025' WHERE id = 1;
UPDATE sics_database.students SET name = 'Sofia Garcia', major = 'Computer Science', email = 'sofia.garcia@example.com', year = '2026' WHERE id = 2;
UPDATE sics_database.students SET name = 'Mohammed Al-Rashid', major = 'Biomedical Engineering', email = 'mohammed.rashid@example.com', year = '2027' WHERE id = 3;
UPDATE sics_database.students SET name = 'Yuki Tanaka', major = 'Molecular Biology', email = 'yuki.tanaka@example.com', year = '2025' WHERE id = 4;
UPDATE sics_database.students SET name = 'Aisha Ahmed', major = 'Environmental Science', email = 'aisha.ahmed@example.com', year = '2026' WHERE id = 5;
UPDATE sics_database.students SET name = 'John Smith', major = 'Political Science', email = 'john.smith@example.com', year = '2027' WHERE id = 6;
UPDATE sics_database.students SET name = 'Maria Gonzalez', major = 'International Relations', email = 'maria.gonzalez@example.com', year = '2025' WHERE id = 7;
UPDATE sics_database.students SET name = 'Chen Wei', major = 'Graphic Design', email = 'chen.wei@example.com', year = '2026' WHERE id = 8;
UPDATE sics_database.students SET name = 'Priya Patel', major = 'Digital Marketing', email = 'priya.patel@example.com', year = '2025' WHERE id = 9;
UPDATE sics_database.students SET name = 'Carlos Mendez', major = 'Computer Science', email = 'carlos.mendez@example.com', year = '2027' WHERE id = 10;
UPDATE sics_database.students SET name = 'Fatima Hassan', major = 'Environmental Science', email = 'fatima.hassan@example.com', year = '2026' WHERE id = 11;
UPDATE sics_database.students SET name = 'Daniel Kim', major = 'Cybersecurity', email = 'daniel.kim@example.com', year = '2027' WHERE id = 12;
UPDATE sics_database.students SET name = 'Katarina Petrova', major = 'Biochemistry', email = 'katarina.petrova@example.com', year = '2025' WHERE id = 13;
UPDATE sics_database.students SET name = 'Amir Abdullah', major = 'Molecular Biology', email = 'amir.abdullah@example.com', year = '2026' WHERE id = 14;
UPDATE sics_database.students SET name = 'Alex Wong', major = 'Biomedical Engineering', email = 'alex.wong@example.com', year = '2027' WHERE id = 15;
UPDATE sics_database.students SET name = 'Ravi Desai', major = 'Environmental Science', email = 'ravi.desai@example.com', year = '2025' WHERE id = 16;
UPDATE sics_database.students SET name = 'Sophia Martinez', major = 'Political Science', email = 'sophia.martinez@example.com', year = '2026' WHERE id = 17;
UPDATE sics_database.students SET name = 'Nathan Brown', major = 'International Relations', email = 'nathan.brown@example.com', year = '2025' WHERE id = 18;
UPDATE sics_database.students SET name = 'Leila Zafar', major = 'Graphic Design', email = 'leila.zafar@example.com', year = '2026' WHERE id = 19;
UPDATE sics_database.students SET name = 'Andre Souza', major = 'Digital Marketing', email = 'andre.souza@example.com', year = '2027' WHERE id = 20;
UPDATE sics_database.students SET name = 'Ella Johansson', major = 'Computer Science', email = 'ella.johansson@example.com', year = '2025' WHERE id = 21;
UPDATE sics_database.students SET name = 'Arjun Singh', major = 'Cybersecurity', email = 'arjun.singh@example.com', year = '2026' WHERE id = 22;
UPDATE sics_database.students SET name = 'Mei Ling', major = 'Biochemistry', email = 'mei.ling@example.com', year = '2027' WHERE id = 23;
UPDATE sics_database.students SET name = 'Emmanuel Okoro', major = 'Molecular Biology', email = 'emmanuel.okoro@example.com', year = '2025' WHERE id = 24;
UPDATE sics_database.students SET name = 'Giulia Rossi', major = 'Biomedical Engineering', email = 'giulia.rossi@example.com', year = '2026' WHERE id = 25;
UPDATE sics_database.students SET name = 'Helena Nunes', major = 'Environmental Science', email = 'helena.nunes@example.com', year = '2027' WHERE id = 26;
UPDATE sics_database.students SET name = 'Michael O’Leary', major = 'Political Science', email = 'michael.oleary@example.com', year = '2025' WHERE id = 27;
UPDATE sics_database.students SET name = 'Kaito Nakamura', major = 'International Relations', email = 'kaito.nakamura@example.com', year = '2026' WHERE id = 28;
UPDATE sics_database.students SET name = 'Pavel Ivanov', major = 'Graphic Design', email = 'pavel.ivanov@example.com', year = '2025' WHERE id = 29;
UPDATE sics_database.students SET name = 'Isabella Santos', major = 'Digital Marketing', email = 'isabella.santos@example.com', year = '2027' WHERE id = 30;
UPDATE sics_database.students SET name = 'Maya Lee', major = 'Computer Science', email = 'maya.lee@example.com', year = '2026' WHERE id = 31;
UPDATE sics_database.students SET name = 'Nina Korhonen', major = 'Cybersecurity', email = 'nina.korhonen@example.com', year = '2025' WHERE id = 32;
UPDATE sics_database.students SET name = 'Derek McKenzie', major = 'Biochemistry', email = 'derek.mckenzie@example.com', year = '2026' WHERE id = 33;
UPDATE sics_database.students SET name = 'Serena Chang', major = 'Molecular Biology', email = 'serena.chang@example.com', year = '2027' WHERE id = 34;
UPDATE sics_database.students SET name = 'Omar Nasser', major = 'Biomedical Engineering', email = 'omar.nasser@example.com', year = '2025' WHERE id = 35;
UPDATE sics_database.students SET name = 'Lucas Johnson', major = 'Environmental Science', email = 'lucas.johnson@example.com', year = '2026' WHERE id = 36;
UPDATE sics_database.students SET name = 'Tara Sharma', major = 'Political Science', email = 'tara.sharma@example.com', year = '2027' WHERE id = 37;
UPDATE sics_database.students SET name = 'Hana Abdi', major = 'International Relations', email = 'hana.abdi@example.com', year = '2025' WHERE id = 38;
UPDATE sics_database.students SET name = 'Boris Zubov', major = 'Graphic Design', email = 'boris.zubov@example.com', year = '2026' WHERE id = 39;
UPDATE sics_database.students SET name = 'Kelsey Davis', major = 'Digital Marketing', email = 'kelsey.davis@example.com', year = '2025' WHERE id = 40;
UPDATE sics_database.students SET name = 'Selina Meyer', major = 'Computer Science', email = 'selina.meyer@example.com', year = '2027' WHERE id = 41;
UPDATE sics_database.students SET name = 'Julian Torres', major = 'Cybersecurity', email = 'julian.torres@example.com', year = '2026' WHERE id = 42;
UPDATE sics_database.students SET name = 'Eva Novak', major = 'Biochemistry', email = 'eva.novak@example.com', year = '2025' WHERE id = 43;
UPDATE sics_database.students SET name = 'Noah Baker', major = 'Molecular Biology', email = 'noah.baker@example.com', year = '2026' WHERE id = 44;
UPDATE sics_database.students SET name = 'Mohammed Qasim', major = 'Biomedical Engineering', email = 'mohammed.qasim@example.com', year = '2027' WHERE id = 45;
UPDATE sics_database.students SET name = 'Sophia Jones', major = 'Environmental Science', email = 'sophia.jones@example.com', year = '2025' WHERE id = 46;
UPDATE sics_database.students SET name = 'Lina Wu', major = 'Political Science', email = 'lina.wu@example.com', year = '2026' WHERE id = 47;
UPDATE sics_database.students SET name = 'Olu Jacobs', major = 'International Relations', email = 'olu.jacobs@example.com', year = '2027' WHERE id = 48;
UPDATE sics_database.students SET name = 'Fatimah Jamal', major = 'Graphic Design', email = 'fatimah.jamal@example.com', year = '2025' WHERE id = 49;
UPDATE sics_database.students SET name = 'Jorge Diaz', major = 'Digital Marketing', email = 'jorge.diaz@example.com', year = '2026' WHERE id = 50;
UPDATE sics_database.students SET name = 'Tatiana Kuznetsov', major = 'Computer Science', email = 'tatiana.kuznetsov@example.com', year = '2027' WHERE id = 51;
